apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
      - name: flask-webapp
        image: 533267040693.dkr.ecr.ap-south-1.amazonaws.com/flask-webapp:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-service
spec:
  type: LoadBalancer
  selector:
    app: flask-webapp
  ports:
  - port: 80
    targetPort: 5000
